# This is a basic workflow to help you get started with Actions
name: testing_workflow

# Controls when the workflow will run
on: [push]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "echo"
  echo:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: update .txt
        run: echo Fran perea quien lo leaaaaa $(date) >log.txt
        
     - name: build firmware
        run: |
         cd stm32f0-discovery_ledblink
         make
         
      - name: Config
        run: |
         git config --global user.email ${{ secrets.mailsecreto }}
         git config --global user.name ${{ secrets.usersecreto }}
         git config --global credential.helper cache
        # to make this work i had to modify the workflow permits in the github page to read and write
      - name: git add .
        run: git add .
        
      - name: git commit
        run: git commit -m "report autogenerated $(date)"
        
      - name: git commit
        run: git push
            
