# This is a basic workflow to help you get started with Actions
name: testing_workflow

# Controls when the workflow will run
on: [push]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "echo"
  echo:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Fran perea quien lo lea $(date) >log.txt
          
     # replaces config htpps for ssh
      - name: returns current user name
        run: who
        
     # - name: is the ssh agent running?
     #   run: ssh-agent -s
            
     # - name: list the public keys
     #   run: sudo ssh-add -l -E sha256
        
     # - name: change remote to ssh fromk https
     #   run: git remote set-url origin git@github.com:javiBajoCero/tryingOutGithubActions.git
        
     # - name: is the ssh reachable?
     #   run: ssh -vT git@github.com     
            
      - name: git config1
        run: git config --global user.email "javier.munoz@luxae.com"
        
      - name: git config2
        run: git config --global user.name "javierMluxae"
        
      - name: git config3
        run:  git config --global credential.helper cache
        
        
      - name: git add .
        run: git add .
        
      - name: git commit
        run: git commit -m "report autogenerated $(date)"
        
      - name: git commit
        run: git push
            
