# This is a basic workflow to help you get started with Actions
name: testing_workflow

# Controls when the workflow will run
on: [push]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "echo"
  echo:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # just a fun text and the date
      - name: update .txt
        run: echo Fran perea quien lo lea $(date) >log.txt
        
      #static checking the code https://www.youtube.com/watch?v=24ajcWSfdaY
      - name: staticcheck
        run: |
         cd stm32f0-discovery_ledblink
         cppcheck --enable=all --error-exitcode=1
         
      #builds/compiles the code, creates the .bin file
      - name: build firmware
        run: |
         cd stm32f0-discovery_ledblink
         make
         
      #flashes firmware to the disrovery board attached to the self-hosted runner
      - name: flash firmware
        run: sudo openocd
        
      - name: Config
        run: |
         git config --global user.email ${{ secrets.mailsecreto }}
         git config --global user.name ${{ secrets.usersecreto }}
         git config --global credential.helper cache
        # to make this work i had to modify the workflow permits in the github page to read and write
      - name: git update changes
        run: |
         git add .
         git commit -m "report autogenerated $(date)"
         git push
